version: '3.8'

services:

  mysql:
    container_name: lf-tests-mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    tmpfs: /var/lib/mysql

  composer:
    image: composer:2.0.3
    environment:
      COMPOSER_CACHE_DIR: /app/var/cache/composer
    volumes:
      - .:/app
    restart: never

  phpunit:
    build:
      context: .
      dockerfile: docker/phpunit/Dockerfile
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit 